.TH GARGOYLE 6 "2011-11-09" "Gargoyle 2011.1"
.SH NAME
gargoyle \- interactive fiction player
.SH SYNOPSIS
.B gargoyle
.I  storyfile
.SH DESCRIPTION
\fBGargoyle\fP is an interpreter for interactive fiction (text
adventure) story files. It supports many different formats, and puts
special emphasis on excellent text rendering.
.PP
See http://ifdb.tads.org/ and http://www.ifarchive.org/ for many free works of
interactive fiction.
.PP
This Fedora package omits support for the Hugo format due to licensing issues.
.SH SEE ALSO
http://ccxvii.net/gargoyle/
.PP
.BR frotz (6)
.SH AUTHOR
Gargoyle was originally developed by Tor Andersson. It is currently
maintained by Ben Cressey; the interpreters it bundles were written
by various authors.
.PP
This manual page was written by Carlo Teubner, based on one
written by Sylvain Beucler for Debian.
